# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

networks:
  local:
    driver: bridge

services:
  ExampleProvider:
    container_name : ExampleProvider
    image          : exampleprovider:local
    tty            : true
    restart        : always
    build          : .

    volumes:
      - .:/usr/src/ExampleProvider
    networks:
      - local
    ports:
      - 3310:3310
