# This tool was written by @keyiflerolsun | for @KekikAkademi

name: CapRover Deployer

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name   : Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 2

      - name: Check for Changes
        id  : check_changes
        run : |
          # Detect changes in relevant file types to trigger deployment
          if git diff --name-only HEAD^ | grep -qE '\.(py|txt|j2|html|css|js|json|yaml|yml)$'; then 
            echo "deploy=true" >> $GITHUB_OUTPUT
          else 
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Deploy TarBall
        if  : steps.check_changes.outputs.deploy == 'true'
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd    : "./"
          files  : ./
          outPath: deploy.tar

      - name: Deploy to CapRover
        if  : steps.check_changes.outputs.deploy == 'true'
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.SERVER }}
          app   : ${{ secrets.PROVIDER_APP }}
          token : ${{ secrets.PROVIDER_TOKEN }}
